api/urls.py
from django.urls import path , include
from api.views import *

urlpatterns = [
    path('register/' , UserRegistrationView.as_view()  , name ='register' ) ,
    path('login/' , UserLoginView.as_view()  , name ='login' ) ,
    path('profile/' , UserProfileView.as_view()  , name ='profile' ) ,
    path('send-reset-password-email/' , SendPasswordResetEmailView.as_view()  , name ='send-reset-password-email' ) ,




    

]

configurations/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('users.urls')),                           #base url for user auth frontend(website)
   

    path('api/user/', include('api.urls')),                                 #base url for user api
    path('api/floodmanagement/', include('api_floodmanagement.urls')),      #base url for floodmanagement api

    path('', include('floodmanagement.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#admin.site.index_title = "Flood manangement administration"
#admin.site.site_header = "Rescue Admin"

floodmanagement/urls.py
from django.contrib import admin
from django.urls import path 
from .views import *

app_name = 'flood'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeListView.as_view(), name='home'),
  
   
       
       
    path('helpmap',  HelpMap, name='HelpMap'),
    path('crowdsourcemap',  CrowdSourceMap, name='CrowdSourceMap'),
    path('crowdsourcelist',  Crowdsource_list, name='Crowdsourcelist'),
    path('deletecs/<int:CrowdSource_id>/' ,deletecs, name='deletecs'),
    path('helplist',  HelpRequest_list, name='HelpRequest_list'),
    path('deletehr/<int:UserHelpRequest_id>/' ,deletehr, name='deletehr'),
    path('update/<int:UserHelpRequest_id>', update, name='update'),
    path('update/updaterecord/<int:UserHelpRequest_id>', updaterecord, name='updaterecord'),
    path('msgpage/', msgpage, name='msgpage'),
    
    path('msgbroadcast/<int:msg_id>', msgupdate, name='msgupdate'),
    path('msgbroadcast/msgbroadcastupdate/<int:msg_id>', msgupdatepage, name='msgupdatepage'),


    path('route',  routefinder, name='routefinder'),

]





    

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import SignUpView, CustomLoginView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),  #URL is using the Django built-in LogoutView
]

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Flood Management System</title>
   <!-- Font Awesome -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
rel="stylesheet"
/>
<!-- Google Fonts -->
<link
href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
rel="stylesheet"
/>
<!-- MDB -->
<link
href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.css"
rel="stylesheet"
/>
  </head>
  <body>




<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand me-2" href="https://mdbgo.com/">
      <img
        src="https://mdbcdn.b-cdn.net/img/logo/mdb-transaprent-noshadows.webp"
        height="16"
        alt="MDB Logo"
        loading="lazy"
        style="margin-top: -1px;"
      />
    </a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'flood:home' %}">Dashboard</a>
        </li>
      </ul>
      <!-- Left links -->
      {% if user.is_authenticated %}

      <div class="d-flex align-items-center">
        <button type="button" class="btn btn-link px-3 me-2">
          Hi {{user.name}}
        </button>
        <a type="button" href="{% url 'user:logout' %}" class="btn btn-danger me-3">
          Logout
        </a>
        {% else %}
        <a type="button" href="{% url 'user:login' %}" class="btn btn-primary me-3">
          Login
        </a>
        {% endif %}
        <a
          class="btn btn-dark px-3"
          href="https://github.com/mdbootstrap/mdb-ui-kit"
          role="button"
          ><i class="fab fa-github"></i
        ></a>
      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->






<!--alert start here-->
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
  {{message}}
  
</div>
{% endfor %}
{% endif %}
<!--alert end here-->   








  
<!--NAVBAR END-->



    <div class="container mt-4">
        {% block content %}



        {% endblock %}

    </div>








    <!-- MDB -->
<script
type="text/javascript"
src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.4.0/mdb.min.js"
></script>
  </body>
</html>

templates/routes.html
{% extends 'base.html' %} 

{% block content %}

{{ my_map|safe }}



{% endblock %}