api/urls.py
from django.urls import path , include
from api.views import *

urlpatterns = [
    path('register/' , UserRegistrationView.as_view()  , name ='register' ) ,
    path('login/' , UserLoginView.as_view()  , name ='login' ) ,
    path('profile/' , UserProfileView.as_view()  , name ='profile' ) ,
    path('send-reset-password-email/' , SendPasswordResetEmailView.as_view()  , name ='send-reset-password-email' ) ,




    

]

configurations/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('users.urls')),                           #base url for user auth frontend(website)
   

    path('api/user/', include('api.urls')),                                 #base url for user api
    path('api/floodmanagement/', include('api_floodmanagement.urls')),      #base url for floodmanagement api

    path('', include('floodmanagement.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#admin.site.index_title = "Flood manangement administration"
#admin.site.site_header = "Rescue Admin"

floodmanagement/urls.py
from django.contrib import admin
from django.urls import path 
from .views import *

app_name = 'flood'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeListView.as_view(), name='home'),
  
   
       
       
    path('helpmap',  HelpMap, name='HelpMap'),
    path('crowdsourcemap',  CrowdSourceMap, name='CrowdSourceMap'),
    path('crowdsourcelist',  Crowdsource_list, name='Crowdsourcelist'),
    path('deletecs/<int:CrowdSource_id>/' ,deletecs, name='deletecs'),
    path('helplist',  HelpRequest_list, name='HelpRequest_list'),
    path('deletehr/<int:UserHelpRequest_id>/' ,deletehr, name='deletehr'),
    path('update/<int:UserHelpRequest_id>', update, name='update'),
    path('update/updaterecord/<int:UserHelpRequest_id>', updaterecord, name='updaterecord'),
    path('msgpage/', msgpage, name='msgpage'),
    
    path('msgbroadcast/<int:msg_id>', msgupdate, name='msgupdate'),
    path('msgbroadcast/msgbroadcastupdate/<int:msg_id>', msgupdatepage, name='msgupdatepage'),


    path('route',  routefinder, name='routefinder'),

]





    

templates/flood/Userhelplist.html
{% extends 'base.html' %} 

{% block content %}



<h6> UserHelpRequest Data </h6>
<div class="btn-group shadow-0" role="group">
    <a type="button"  href="{% url 'flood:HelpRequest_list' %}" class="btn btn-link" data-mdb-color="dark">Refresh Page</a>
    <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Home</a>
    <a type="button"  href="{% url 'flood:HelpMap' %}" class="btn btn-link" data-mdb-color="dark">Map</a>


</div>

<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>Name</th>
        <th>Time Stamp</th>
        <th>View on Map</th>
        <th>Position(Long/lat)</th>
        <th>Actions(Delete)</th>
        <th>Actions(Update)</th>
      </tr>
    </thead>
    {% for helpeobject in object_list %}
    <tbody>
      <tr>
        <td>
          <div class="d-flex align-items-center">
            <img
                src="https://yt3.ggpht.com/ytc/AMLnZu-D_TGDEkHSn_7bqS5JirQby30OpXyy4C3MrmRh=s900-c-k-c0x00ffffff-no-rj"
                alt=""
                style="width: 45px; height: 45px"
                class="rounded-circle"
                />
            <div class="ms-3">
              <p class="fw-bold mb-1">{{helpeobject.owner}}</p>
              <p class="text-muted mb-0"><strong>Emergency Type :</strong> {{helpeobject.TypeOfEmergency}}</p>
              <p class="text-muted mb-0"><strong>Request Status :</strong> {{helpeobject.RequestStatus}}</p>

            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1">{{helpeobject.description}}</p>
          <p class="text-muted mb-0"><strong>Created_at :</strong> {{helpeobject.created_at}} <br> <strong>Updated_at :</strong> {{helpeobject.updated_at}}</p>
        </td>
        <td>
          <a type="button" class="btn btn-link btn-sm btn-rounded" href = "{% url 'flood:HelpMap' %}" > click to View  </a>
        </td>
        <td>{{helpeobject.longitude}} <br>{{helpeobject.latitude}} </td>
        <td><form action="{% url 'flood:deletehr' helpeobject.id %}"
            method="post" class="d-inline">{% csrf_token %}
            <input type="submit" class="btn btn-danger btn-sm" value="Delete">
            </form></td>
        <td><form action="{% url 'flood:update' helpeobject.id %}"
            method="post" class="d-inline">{% csrf_token %}
            <input type="submit" class="btn btn-info btn-sm" value="Update">
            </form></td>
      </tr>
     
{% endfor %}
      
    </tbody>
  </table>




























{% endblock %}

templates/flood/create.html
{% extends 'base.html' %} 

{% block content %}

{% load crispy_forms_tags %}

<div class="mx-auto">
  <h1 class="mt-3 text-center">Add photo</h1>
</div>
<div class="form-group">
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success mb-3">Add Photo</button>
  </form>
</div>

{% endblock %}

templates/flood/crowdsourcelist.html
{% extends 'base.html' %} 

{% block content %}



<h6> CrowdSource Data </h6>

<div class="btn-group shadow-0" role="group">
  <a type="button"  href="{% url 'flood:Crowdsourcelist' %}" class="btn btn-link" data-mdb-color="dark">Refresh Page</a>
  <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Home</a>
  <a type="button"  href="{% url 'flood:CrowdSourceMap' %}" class="btn btn-link" data-mdb-color="dark">Maps</a>

</div>



<table class="table align-middle mb-0 bg-white">
    <thead class="bg-light">
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>View on Map</th>
        <th>Position(Long/lat)</th>
        <th>Actions</th>
      </tr>
    </thead>
    {% for crowdsourceobject in object_list %}
    <tbody>
      <tr>
        <td>
          <div class="d-flex align-items-center">
            <a href="{{crowdsourceobject.image.url }}" target="_blank">
            <img
                src="{{crowdsourceobject.image.url }}"
                alt=""
                style="width: 45px; height: 45px"
                class="rounded-circle"
                />
              </a>
            <div class="ms-3">
              <p class="fw-bold mb-1">{{crowdsourceobject.owner}}</p>
              <p class="text-muted mb-0"><strong>Emergency Type :</strong> {{crowdsourceobject.category}}</p>
            </div>
          </div>
        </td>
        <td>
          <p class="fw-normal mb-1">{{crowdsourceobject.description}}</p>
          <p class="text-muted mb-0"><strong>Created_at :</strong> {{crowdsourceobject.created_at}}</p>
        </td>
        <td>
          <a type="button" class="btn btn-link btn-sm btn-rounded" href = "{% url 'flood:CrowdSourceMap' %}" > click to View  </a>
        </td>
        <td>{{crowdsourceobject.longitude}} <br>{{crowdsourceobject.latitude}} </td>
        <td><form action="{% url 'flood:deletecs' crowdsourceobject.id %}"
            method="post" class="d-inline">{% csrf_token %}
            <input type="submit" class="btn btn-danger btn-sm" value="Delete">
            </form></td>
      </tr>
     
{% endfor %}
      
    </tbody>
  </table>




























{% endblock %}

templates/flood/crowdsourcemap.html
{% extends 'base.html' %} 

{% block content %}

<div class="btn-group shadow-0" role="group">
    <a type="button"  href="{% url 'flood:CrowdSourceMap' %}" class="btn btn-link" data-mdb-color="dark">Refresh Page</a>
    <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Home</a>
    <a type="button"  href="{% url 'flood:Crowdsourcelist' %}" class="btn btn-link" data-mdb-color="dark">Back to Admin</a>
  
  </div>









        {{ my_map|safe }}
        <script src="" async defer></script>
    </body>




    {% endblock %}

templates/flood/deleted_successfully.html
{% extends 'base.html' %} 

{% block content %}



   <!--alert start here-->
   {% if messages %}
   {% for message in messages %}
   <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
     {{message}}
    
   {% endfor %}
   {% endif %}
   <!--alert end here--> 


{% endblock %}

templates/flood/helpmap.html
{% extends 'base.html' %} 

{% block content %}

    
  
  <div class="btn-group shadow-0" role="group">
    <a type="button"  href="{% url 'flood:HelpMap' %}" class="btn btn-link" data-mdb-color="dark">Refresh Page</a>
    <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Home</a>
    <a type="button"  href="{% url 'flood:HelpRequest_list' %}" class="btn btn-link" data-mdb-color="dark">Back to Admin</a>


</div>



        {{ my_map|safe }}
        <script src="" async defer></script>
    </body>




    {% endblock %}

templates/flood/home.html
{% extends 'base.html' %} 

{% block content %}


<div class="list-group list-group-light">
  <a
    href="{% url 'admin:index' %}"
    class="list-group-item list-group-item-action px-3 border-0 active"
    aria-current="true"
    >⚠️ Open Admin Panel </a
  >
  <a
    href="{% url 'flood:HelpRequest_list' %}"
    class="list-group-item list-group-item-action px-3 border-0 "
    >View HelpRequest data</a
  >
  <a
    href="{% url 'flood:HelpMap' %}"
    class="list-group-item list-group-item-action px-3 border-0"
    >🗺️ View Help Request Map  </a
  >
  <a
    href="{% url 'flood:Crowdsourcelist' %}"
    class="list-group-item list-group-item-action px-3 border-0"
    >View CrowdSource data </a
  >
  <a
    href="{% url 'flood:CrowdSourceMap' %}"
    class="list-group-item list-group-item-action px-3 border-0"
    >🗺️ View CrowdSource Maps </a
  >
  <a
    href="{% url 'flood:msgpage' %}"
    class="list-group-item list-group-item-action px-3 border-0"
    >✉️ BroadCast Message  </a
  >
  
  
</div>















{% endblock %}

templates/flood/msgpage.html
{% extends 'base.html' %} 

{% block content %}



<div class="btn-group shadow-0" role="group">
 
  <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Home</a>
  <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Back to Admin</a>


</div>



<div class="card">
    <div class="card-body">
      <h5 class="card-title">Message broadcast Sent at : {{msgdata.msg}} </h5>
     
      <form action="{% url 'flood:msgupdate' msgdata.id %}"
      method="post" class="d-inline">{% csrf_token %}
      <input type="submit" class="btn btn-info btn-sm" value="Update">
      </form></td>
      







{% endblock %}

templates/flood/msgupdate.html
{% extends 'base.html' %} 

{% block content %}



<div class="btn-group shadow-0" role="group">
 
  <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Home</a>
  <a type="button"  href="{% url 'flood:home' %}" class="btn btn-link" data-mdb-color="dark">Back to Admin</a>


</div>


<form action="msgbroadcastupdate/{{ msgdata.id }}" method="post">
    {% csrf_token %}

<div class="card">
    <div class="card-body">
      <h5 class="card-title">Message broadcast Sent at : {{msgdata.created_at}} </h5>
      <h5 class="card-title">Your Message : <p style ="color: Red ">{{msgdata.msg}}</p> </h5>
      <p class="card-text">
        
        <input class="form-select" aria-label="Default select example" name="msgstatus">
            
 

      </p>
      <button type="Submit" class="btn btn-primary">Update</button>
    </div>
  </div>

</form>









{% endblock %}

templates/flood/update.html
{% extends 'base.html' %} 

{% block content %}






<form action="updaterecord/{{ Helpdata.id }}" method="post">
    {% csrf_token %}

<div class="card">
    <div class="card-body">
      <h5 class="card-title">Owner : {{Helpdata.owner}} || Id : {{ Helpdata.id }}</h5>
      <p class="card-text">
        Update User Request Status{{ Helpdata.id }}
        <select class="form-select" aria-label="Default select example" name="RequestStatus">
            <option selected>{{ Helpdata.RequestStatus }}</option>
            <option value="HELP ALERT SEND TO AUTHORITIES">HELP ALERT SEND TO AUTHORITIES</option>
            <option value="HELP TO YOUR LOCATION DEPLOYED">HELP TO YOUR LOCATION DEPLOYED</option>
            <option value="OPERATION COMPLETED">OPERATION COMPLETED</option>
          </select>

      </p>
      <button type="Submit" class="btn btn-primary">Update</button>
    </div>
  </div>

</form>









{% endblock %}