api/urls.py
from django.urls import path , include
from api.views import *

urlpatterns = [
    path('register/' , UserRegistrationView.as_view()  , name ='register' ) ,
    path('login/' , UserLoginView.as_view()  , name ='login' ) ,
    path('profile/' , UserProfileView.as_view()  , name ='profile' ) ,
    path('send-reset-password-email/' , SendPasswordResetEmailView.as_view()  , name ='send-reset-password-email' ) ,




    

]

configurations/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authenticate/', include('users.urls')),                           #base url for user auth frontend(website)
   

    path('api/user/', include('api.urls')),                                 #base url for user api
    path('api/floodmanagement/', include('api_floodmanagement.urls')),      #base url for floodmanagement api

    path('', include('floodmanagement.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),




]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#admin.site.index_title = "Flood manangement administration"
#admin.site.site_header = "Rescue Admin"

users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import SignUpView, CustomLoginView

app_name = 'user'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),  #URL is using the Django built-in LogoutView
]

users/models.py
from django.db import models

from django.contrib.auth import get_user_model
# Create your models here.



#class Photo(models.Model):

    #latitude = models.DecimalField(max_digits=19, decimal_places=16)
   # longitude = models.DecimalField(max_digits=19, decimal_places=16)

    #submitter = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)


 

  #  def __str__(self):
       # return self.title

users/views.py
from django.views.generic import CreateView
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy


class SignUpView(CreateView):

    template_name = 'users/signup.html'

    form_class = UserCreationForm

    success_url = reverse_lazy('flood:home')  #app:url/template

    def form_valid(self, form):
        to_return = super().form_valid(form)

        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )

        login(self.request, user)

        return to_return

class CustomLoginView(LoginView):

    template_name = 'users/login.html'

templates/users/login.html
{% extends 'base.html' %} 

{% block content %}

{% load crispy_forms_tags %}



<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-success w-100 my-3">Sign in</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Don't have an account?
      <a href="{% url 'user:signup' %}" class="text-primary ml-2">Create account</a>
    </p>
  </div>
</div>

{% endblock %}

templates/users/signup.html
{% extends 'base.html' %}
{% block content %}





{% load crispy_forms_tags %}

<div class="mx-auto">
  <div class="form-group">
    <form action="" method="post">
      {% csrf_token %} 
      {{ form|crispy }}
      <button type="submit" class="btn btn-success w-100 my-3">Create account</button>
    </form>
  </div>
  {% comment %}  Already Registered {% endcomment %}
  <div class="text-center w-100">
    <p class="text-muted font-weight-bold">
      Already Registered?
      <a href="{% url 'user:login' %}" class="text-primary ml-2"> Login </a>
    </p>
  </div>
</div>















{% endblock %}